### ISSUE TITLE
Exit with failure code or success when there were errors converted?

### ISSUE THREAD

**Issue by ttomdewit** [beechit/json-to-code-climate-subset-converter#19]
At the moment the converter command will exit with exit code 0 (https://github.com/beechit/json-to-code-climate-subset-converter/blob/master/src/Command/ConverterCommand.php#L30) when everything went as expected.

However, is it desirable to exit with code 0 when there were no errors converted to the Code Climate subset? And exit with any other code when the converting went successfully, but there were errors converted? This will fail the job in your pipeline, stopping any other pipelines that follow.

**Comment by Brunty** [comment]
If it changes downstream behaviour and requires the user to change something because of a change you've made, then it's considered a BC break.

If you want to give the option to exit with a different status if errors are converted, perhaps a flag to do so could work? It doesn't affect existing users, but adds a new feature to allow different behaviour (thus, not affecting existing users)

`--fail-on-convert` (or whatever naming is appropriate) perhaps?

**Comment by ttomdewit** [comment]
> If it changes downstream behaviour and requires the user to change something because of a change you've made, then it's considered a BC break.
> 
> 
> 
> If you want to give the option to exit with a different status if errors are converted, perhaps a flag to do so could work? It doesn't affect existing users, but adds a new feature to allow different behaviour (thus, not affecting existing users)
> 
> 
> 
> `--fail-on-convert` (or whatever naming is appropriate) perhaps?

I very much like this idea. For a new major release we might consider a new exit code, but for now a flag sounds like the path to take.

I'll think about the correct naming and release it as a minor patch in the next few days.
